# version: "3.8"

services:
  tmh-api:
    build: .
    container_name: tmh-container
    ports:
      - "8000:8000"
    restart: always             # <--- ici
    environment:
      - DATA_ROOT=/app/Reports
    volumes:
      - ./Reports:/app/Reports
      - ./uploads:/app/uploads
      - ./Config:/app/Config
