version: "3.8"

services:
  tmh-api:
    build: .
    container_name: tmh-container
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./reports:/app/reports
      - ./uploads:/app/uploads
      - ./Config:/app/Config
