version: "3.8"

services:
  tmh-api:
    build: .
    container_name: tmh-container
    ports:
      - "8000:8000"
    volumes:
      - ./configs:/app/configs
      - ./uploads:/app/uploads
    restart: unless-stopped

